-- Migration: add thinking_text to chat_messages
-- Stores the safe public-facing Thinking Mode narrative generated by the
-- planner streamed to the user.  NULL when Thinking Mode is disabled.
-- Safe to run multiple times (uses IF NOT EXISTS pattern).

ALTER TABLE public.chat_messages
ADD COLUMN IF NOT EXISTS thinking_text TEXT DEFAULT NULL;

COMMENT ON COLUMN public.chat_messages.thinking_text IS
'Safe public-facing Thinking Mode narrative generated by the planner. NULL when Thinking Mode is disabled.';
