-- [VECTOR REINDEX]
-- Migration to add vector index health check monitoring and metadata tracking

-- Ensure pg_cron is enabled for background execution outside transaction blocks
create extension if not exists pg_cron; -- [VECTOR REINDEX]

-- Create metadata table to track index builds
create table if not exists public.vector_index_metadata ( -- [VECTOR REINDEX]
    id integer primary key default 1 check (id = 1), -- [VECTOR REINDEX]
    last_reindex_at timestamp with time zone not null default timezone('utc'::text, now()), -- [VECTOR REINDEX]
    rows_at_last_reindex bigint not null default 0 -- [VECTOR REINDEX]
); -- [VECTOR REINDEX]

-- Seed metadata row with current count
insert into public.vector_index_metadata (id, last_reindex_at, rows_at_last_reindex) -- [VECTOR REINDEX]
select 1, timezone('utc'::text, now()), count(*) -- [VECTOR REINDEX]
from public.document_embeddings -- [VECTOR REINDEX]
on conflict (id) do nothing; -- [VECTOR REINDEX]

-- Function to check vector index health
create or replace function public.get_vector_index_health( -- [VECTOR REINDEX]
  out total_rows bigint, -- [VECTOR REINDEX]
  out rows_at_last_reindex bigint, -- [VECTOR REINDEX]
  out rows_added bigint, -- [VECTOR REINDEX]
  out last_reindex_at timestamp with time zone, -- [VECTOR REINDEX]
  out needs_reindex boolean -- [VECTOR REINDEX]
) -- [VECTOR REINDEX]
language plpgsql -- [VECTOR REINDEX]
security definer -- [VECTOR REINDEX]
set search_path = public -- [VECTOR REINDEX]
as $$ -- [VECTOR REINDEX]
declare -- [VECTOR REINDEX]
  v_current_count bigint; -- [VECTOR REINDEX]
  v_last_count bigint; -- [VECTOR REINDEX]
  v_last_time timestamp with time zone; -- [VECTOR REINDEX]
begin -- [VECTOR REINDEX]
  select count(*) into v_current_count from public.document_embeddings; -- [VECTOR REINDEX]
   -- [VECTOR REINDEX]
  select m.rows_at_last_reindex, m.last_reindex_at -- [VECTOR REINDEX]
  into v_last_count, v_last_time -- [VECTOR REINDEX]
  from public.vector_index_metadata m -- [VECTOR REINDEX]
  where m.id = 1; -- [VECTOR REINDEX]
   -- [VECTOR REINDEX]
  if not found then -- [VECTOR REINDEX]
    v_last_count := 0; -- [VECTOR REINDEX]
    v_last_time := null; -- [VECTOR REINDEX]
  end if; -- [VECTOR REINDEX]

  total_rows := v_current_count; -- [VECTOR REINDEX]
  rows_at_last_reindex := v_last_count; -- [VECTOR REINDEX]
  rows_added := greatest(0, v_current_count - v_last_count); -- [VECTOR REINDEX]
  last_reindex_at := v_last_time; -- [VECTOR REINDEX]
   -- [VECTOR REINDEX]
  if v_last_count > 0 then -- [VECTOR REINDEX]
    needs_reindex := (rows_added::double precision / v_last_count::double precision) > 0.30; -- [VECTOR REINDEX]
  else -- [VECTOR REINDEX]
    needs_reindex := v_current_count > 0; -- [VECTOR REINDEX]
  end if; -- [VECTOR REINDEX]
end; -- [VECTOR REINDEX]
$$; -- [VECTOR REINDEX]

-- Function to trigger manual reindexing concurrently via pg_cron
create or replace function public.trigger_vector_index_reindex() -- [VECTOR REINDEX]
returns text -- [VECTOR REINDEX]
language plpgsql -- [VECTOR REINDEX]
security definer -- [VECTOR REINDEX]
set search_path = public -- [VECTOR REINDEX]
as $$ -- [VECTOR REINDEX]
declare -- [VECTOR REINDEX]
  v_job_id bigint; -- [VECTOR REINDEX]
begin -- [VECTOR REINDEX]
  -- Check if pg_cron extension is installed and schema exists -- [VECTOR REINDEX]
  if not exists ( -- [VECTOR REINDEX]
    select 1  -- [VECTOR REINDEX]
    from pg_extension  -- [VECTOR REINDEX]
    where extname = 'pg_cron' -- [VECTOR REINDEX]
  ) then -- [VECTOR REINDEX]
    raise exception 'pg_cron extension is not enabled in this database. Please enable it by running "create extension pg_cron;" in the SQL Editor.'; -- [VECTOR REINDEX]
  end if; -- [VECTOR REINDEX]

  -- Unschedule any previous manual reindex jobs to avoid duplication -- [VECTOR REINDEX]
  perform cron.unschedule(jobname)  -- [VECTOR REINDEX]
  from cron.job  -- [VECTOR REINDEX]
  where jobname = 'manual_vector_reindex'; -- [VECTOR REINDEX]

  -- Schedule the reindex to run concurrently in the background. -- [VECTOR REINDEX]
  -- pg_cron will execute this outside the HTTP/Postgrest transaction. -- [VECTOR REINDEX]
  -- Once the index rebuild finishes, we update the metadata table and unschedule the cron. -- [VECTOR REINDEX]
  select cron.schedule( -- [VECTOR REINDEX]
    'manual_vector_reindex', -- [VECTOR REINDEX]
    '* * * * *', -- [VECTOR REINDEX]
    'REINDEX INDEX CONCURRENTLY public.document_embeddings_embedding_idx; UPDATE public.vector_index_metadata SET last_reindex_at = now(), rows_at_last_reindex = (SELECT count(*) FROM public.document_embeddings) WHERE id = 1; SELECT cron.unschedule(''manual_vector_reindex'');' -- [VECTOR REINDEX]
  ) into v_job_id; -- [VECTOR REINDEX]

  return 'Reindexing scheduled concurrently in the background via pg_cron. Job ID: ' || v_job_id; -- [VECTOR REINDEX]
end; -- [VECTOR REINDEX]
$$; -- [VECTOR REINDEX]

-- Explicitly revoke execution on SECURITY DEFINER functions from PUBLIC  -- [VECTOR REINDEX]
revoke execute on function public.get_vector_index_health() from public;  -- [VECTOR REINDEX]
revoke execute on function public.trigger_vector_index_reindex() from public;  -- [VECTOR REINDEX]

-- Grant execution permissions only to authorized service_role and postgres roles  -- [VECTOR REINDEX]
grant execute on function public.get_vector_index_health() to service_role;  -- [VECTOR REINDEX]
grant execute on function public.get_vector_index_health() to postgres;  -- [VECTOR REINDEX]

grant execute on function public.trigger_vector_index_reindex() to service_role;  -- [VECTOR REINDEX]
grant execute on function public.trigger_vector_index_reindex() to postgres;  -- [VECTOR REINDEX] -- [VECTOR REINDEX]
