'use client'; // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
import { motion } from "framer-motion"; // [QUICK ACTION CARDS]
import { Layers, ClipboardList, ScanSearch, Sparkles, GraduationCap } from "lucide-react"; // [QUICK ACTION CARDS]
import type { LucideIcon } from "lucide-react"; // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
interface QuickActionCardConfig { // [QUICK ACTION CARDS]
  id: string; // [QUICK ACTION CARDS]
  title: string; // [QUICK ACTION CARDS]
  description: string; // [QUICK ACTION CARDS]
  icon: LucideIcon; // [QUICK ACTION CARDS]
  modalLabel: string; // [QUICK ACTION CARDS]
  hasCountSelector: boolean; // [QUICK ACTION CARDS]
  buildPrompt: (input: string, count?: number) => string; // [QUICK ACTION CARDS]
} // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
export const QUICK_ACTION_CARDS = [ // [QUICK ACTION CARDS]
  { // [QUICK ACTION CARDS]
    id: "break-it-down", // [QUICK ACTION CARDS]
    title: "Break down", // [QUICK ACTION CARDS]
    description: "Understand any drug or concept from first principles", // [QUICK ACTION CARDS]
    icon: Layers, // [QUICK ACTION CARDS]
    modalLabel: "What drug or concept?", // [QUICK ACTION CARDS]
    hasCountSelector: false, // [QUICK ACTION CARDS]
    buildPrompt: (input: string) => `Explain ${input} to me like I'm encountering it for the first time. Cover the mechanism, why it matters pharmacologically, and one thing students consistently get wrong about it. Calibrate the depth and any clinical context based on my current level.`, // [QUICK ACTION CARDS]
  }, // [QUICK ACTION CARDS]
  { // [QUICK ACTION CARDS]
    id: "quiz-me", // [QUICK ACTION CARDS]
    title: "Quiz me", // [QUICK ACTION CARDS]
    description: "Test your understanding with targeted MCQs", // [QUICK ACTION CARDS]
    icon: ClipboardList, // [QUICK ACTION CARDS]
    modalLabel: "What topic?", // [QUICK ACTION CARDS]
    hasCountSelector: true, // [QUICK ACTION CARDS]
    buildPrompt: (input: string, count: number = 5) => `Generate ${count} MCQs on ${input} that test understanding, not memorization. Present them one at a time. After I answer each one, explain the concept behind it fully - not just correct or incorrect.`, // [QUICK ACTION CARDS]
  }, // [QUICK ACTION CARDS]
  { // [QUICK ACTION CARDS]
    id: "weak-spot-finder", // [QUICK ACTION CARDS]
    title: "Weak spots", // [QUICK ACTION CARDS]
    description: "Find exactly where your understanding breaks down", // [QUICK ACTION CARDS]
    icon: ScanSearch, // [QUICK ACTION CARDS]
    modalLabel: "What topic do you think you understand?", // [QUICK ACTION CARDS]
    hasCountSelector: false, // [QUICK ACTION CARDS]
    buildPrompt: (input: string) => `Ask me 3 probing questions on ${input} one at a time. After I've answered all three, give me an honest breakdown of exactly where my understanding is solid and where the gaps are. Don't go easy on me.`, // [QUICK ACTION CARDS]
  }, // [QUICK ACTION CARDS]
  { // [QUICK ACTION CARDS]
    id: "mnemonics-memory", // [QUICK ACTION CARDS]
    title: "Mnemonics", // [QUICK ACTION CARDS]
    description: "Turn hard-to-remember facts into things that stick", // [QUICK ACTION CARDS]
    icon: Sparkles, // [QUICK ACTION CARDS]
    modalLabel: "What do you need to memorize?", // [QUICK ACTION CARDS]
    hasCountSelector: false, // [QUICK ACTION CARDS]
    buildPrompt: (input: string) => `Help me memorize ${input} using mnemonics, acronyms, patterns, or memorable stories. Focus especially on the things that are notoriously hard to retain in pharmacy.`, // [QUICK ACTION CARDS]
  }, // [QUICK ACTION CARDS]
  { // [QUICK ACTION CARDS]
    id: "teach-it-back", // [QUICK ACTION CARDS]
    title: "Teach back", // [QUICK ACTION CARDS]
    description: "Prove you really know it by teaching it to the AI", // [QUICK ACTION CARDS]
    icon: GraduationCap, // [QUICK ACTION CARDS]
    modalLabel: "What topic do you want to teach?", // [QUICK ACTION CARDS]
    hasCountSelector: false, // [QUICK ACTION CARDS]
    buildPrompt: (input: string) => `Play the role of a confused pharmacy student who just attended a lecture on ${input} and didn't fully understand it. Ask me genuine questions a struggling student would ask - one at a time. After I've explained it to you, evaluate my explanation honestly: what was accurate, what was missing, and what was wrong. End with a clear summary of my gaps.`, // [QUICK ACTION CARDS]
  }, // [QUICK ACTION CARDS]
] as const satisfies readonly QuickActionCardConfig[]; // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
export type QuickActionCard = typeof QUICK_ACTION_CARDS[number]; // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
interface QuickActionCardsProps { // [QUICK ACTION CARDS]
  onCardClick: (card: typeof QUICK_ACTION_CARDS[number]) => void; // [QUICK ACTION CARDS]
} // [QUICK ACTION CARDS]
 // [QUICK ACTION CARDS]
export function QuickActionCards({ onCardClick }: QuickActionCardsProps) { // [QUICK ACTION CARDS]
  return ( // [QUICK ACTION CARDS]
    <div className="w-full px-4 pt-2 pb-1"> {/* [QUICK ACTION CARDS] */}
      <div className="flex flex-wrap justify-center gap-2"> {/* [QUICK ACTION CARDS] */}
        {QUICK_ACTION_CARDS.map((card, index) => { /* [QUICK ACTION CARDS] */
          const Icon = card.icon; // [QUICK ACTION CARDS]
          return ( // [QUICK ACTION CARDS]
            <motion.button // [QUICK ACTION CARDS]
              key={card.id} // [QUICK ACTION CARDS]
              type="button" // [QUICK ACTION CARDS]
              whileHover={{ scale: 1.02 }} // [QUICK ACTION CARDS]
              transition={{ duration: 0.15 }} // [QUICK ACTION CARDS]
              onClick={() => onCardClick(card)} // [QUICK ACTION CARDS]
              className="inline-flex h-8 shrink-0 items-center gap-1.5 rounded-[6px] border border-border/60 bg-card px-3 text-sm font-medium text-foreground shadow-sm cursor-pointer transition-colors hover:bg-muted" // [QUICK ACTION CARDS]
            > {/* [QUICK ACTION CARDS] */}
              <Icon className="h-4 w-4 text-muted-foreground" /> {/* [QUICK ACTION CARDS] */}
              <span>{card.title}</span> {/* [QUICK ACTION CARDS] */}
              {/* [QUICK ACTION CARDS] */}</motion.button>
          ); // [QUICK ACTION CARDS]
        })} {/* [QUICK ACTION CARDS] */}
      </div> {/* [QUICK ACTION CARDS] */}
      {/* [QUICK ACTION CARDS] */}</div>
  ); // [QUICK ACTION CARDS]
} // [QUICK ACTION CARDS]
